namespace Harmony.Domain.Enums
{
    public enum NotificationType
    {
        CardMoved,
        CardCreated,
        CardTitleChanged,
        CardDescriptionChanged,
        CardDatesChanged,
        CardItemAdded,
        CardIssueTypeChanged,
        BoardListTitleChanged,
        BoardListsPositionChanged,
        BoardListArchived,
        SubTaskStoryPointsChanged,
        BoardListCreated,
        CardItemCheckedChanged,
        CardLabelRemoved,
        CardLabelToggled,
        CardStoryPointsChanged,
        CardStatusChanged,
        CardAttachmentAdded,
        CardAttachmentRemoved,
        CardMemberRemoved,
        CardMemberAdded,
        CheckListRemoved,
        CardCommentCreated,
        CardCommentDeleted,
        CardLinkCreated,
        CardLinkDeleted,
        BranchCreated,
        BranchCommitsPushed,
        BranchPullRequestCreated
    }
}
